- matchers:
    - deployment="gambia"
    - environment="uat"
  receiver: slack-gambia-uat
  routes:
    - matchers:
        - severity="critical"
      receiver: slack-gambia-uat
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 4h
- matchers:
    - deployment="malawi"
    - environment="uat"
  receiver: slack-malawi-uat
  routes:
    - matchers:
        - severity="critical"
      receiver: slack-malawi-uat
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 4h
- matchers:
    - deployment="malawi"
    - environment="prod"
  receiver: slack-malawi-prod
  routes:
    - matchers:
        - severity="critical"
      receiver: slack-malawi-prod
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 4h
